# -*- coding: utf-8 -*-
"""Cadastro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tGtc5h5sA_D15P4aNjWcuTRFTl41ZXDs

#Automation
"""

#instalar vscode > abrir pasta onde baixou os arquivos/ link da empresa está na descrição

#1: entrar no sistema
#2: login
#3: importar db
#4: cadastrar 1 produto
#5: repetir o processo de cadastro até acabar

#1:
import pyautogui (instalar no cmd) pip install import time

pyautogui.PAUSE = 1 #varie para otimizar

(principais comandos:)
pyautogui.click
pyautogui.write
pyautogui.press
pyautogui.hotkey('key1', 'key2')


#abrir o chrome
pyautogui.press('win')
pyautogui.write('chrome')
pyautogui.press('enter')

link = '...'
pyautogui.write(link)
pyautogui.press('enter')

time.sleep(3)

#2:

time.sleep(5)
print(pyautogui.position()) #põe o mouse na posição
pos = pyautogui.position()
pyautogui.click(pos)
pyautogui.write('pythonimpressionador@gmail.com')

pyautogui.press('tab')
pyautogui.write('sua senha aqui')

pos = pyautogui.position()#logar
pyautogui.click(pos)
time.sleep(3)

#3:
pip install pandas numpy openpyxl (cmd)
import pandas as pd

path = '..'
tabela = pd.read_csv(path)



#5

for linha in tabela.index:
	pyautogui.click(pos)
	cod_produto = tabela.loc[linha, 'codigo']
	pyautogui.write(cod_produto)
	pyautogui.press('tab')

	marca = tabela.loc[linha, 'marca']
	pyautogui.write(marca)
	pyautogui.press('tab')

	tipo = tabela.loc[linha, 'tipo']
	pyautogui.write(tipo)
	pyautogui.press('tab')

	categoria = str(tabela.loc[linha, 'categoria'])
	pyautogui.write(categoria)
	pyautogui.press('tab')

	preco = str(tabela.loc[linha, 'preco_unitario'])
	pyautogui.write(preco)
	pyautogui.press('tab')

	custo = str(tabela.loc[linha, 'custo'])
	pyautogui.write(custo)
	pyautogui.press('tab')

	if not tabela.loc[linha, 'OBS'].isna():
		OBS = tabela.loc[linha, 'OBS']
		pyautogui.write(OBS)

	pyautogui.press('tab')

	pyautogui.press('enter')
	time.sleep(2)
	pyautogui.scroll(5000) #ngrande pro início da tela